name: Update IOCs from OTX

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-iocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install requests
      - name: Run update script
        env:
          OTX_API_KEY: ${{ secrets.OTX_API_KEY }}
        run: python IOCIntel/update_iocs.py
      - name: Commit & push changes (if any)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add IOCIntel/ .state/otx_last_success.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update IOCs from AlienVault OTX"
            git push "https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git" HEAD:main
          fi

